name: Build

run-name: Building -- ${{github.head_ref || github.ref_name }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'

      - name: Make Dockerfile
        run: |
          echo ${secrets.DOCKERFILE} >> Dockerfile

      - name: Build Code
        run: mvn clean install

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: target/*.jar*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: acompletenoobsmoke/javapractice:latest
