name: Build

run-name: Building -- ${{github.head_ref || github.ref_name }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'

      - name: Build Code
        run: mvn clean install